# Generated by Django 3.0 on 2020-07-26 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('reference', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Asset Reference')),
                ('city', models.CharField(max_length=254, verbose_name='City')),
                ('address', models.CharField(max_length=254, verbose_name='Address')),
                ('zipcode', models.IntegerField(verbose_name='Zip Code')),
                ('is_restricted', models.BooleanField(default=False, verbose_name='Is Restricted')),
                ('year_of_construction', models.PositiveIntegerField(help_text='Use the following format: YYYY', validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2020)], verbose_name='Year Of Construction')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': '-updated_at',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Portfolio Name')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': '-updated_at',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('unit_type', models.CharField(choices=[('rs', 'Residential'), ('cm', 'Commercial'), ('of', 'Office'), ('rt', 'Retail')], max_length=2, verbose_name='Type')),
                ('reference', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Unit Reference')),
                ('is_rented', models.BooleanField(default=False, verbose_name='Is rented?')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('rent', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=12, null=True, verbose_name='Rent')),
                ('tenant', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Tenant')),
                ('lease_start', models.DateField(blank=True, db_index=True, default='', null=True, verbose_name='Lease Start')),
                ('lease_end', models.DateField(blank=True, db_index=True, default='', null=True, verbose_name='Lease End')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.Asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': '-updated_at',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.Portfolio', verbose_name='Portfolio'),
        ),
    ]
